name: Test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"
      - run: python3 -m pip install -r requirements-dev.txt
      - run: pytest --cov=custom_components
